### PR TITLE
not a root of hierarchy

### PR DESCRIPTION
**Pull request by Pavneet-Sing**
https://developer.android.com/reference/android/view/LayoutInflater.html#inflate%28org.xmlpull.v1.XmlPullParser,%20android.view.ViewGroup,%20boolean%29

### CODE REVIEW

**Review by thedumbtechguy — COMMENTED** [review]
`attachToRoot` is only required if you provide a root. 
Since we are passing `null`, it's not required.

**Comment by Pavneet-Sing** [comment]
i was just trying to save an extra method call because this

> View view = LayoutInflater.from(viewGroup.getContext()).inflate(R.layout.todoitem, null);


will internally call to this

> View view = LayoutInflater.from(viewGroup.getContext()).inflate(R.layout.todoitem, null, false);


something like

> 
>    inflate(int resource, ViewGroup root) {
>         return inflate(resource, root, root != null);

**Comment by thedumbtechguy** [comment]
A negligible gain if you ask me.
I do appreciate the contribution though.

Do tell me what you think about the project though.

**Comment by Pavneet-Sing** [comment]
With doubt , i like the concept of immutability and cute builder patterns .it is a great work and very well explained.

**Comment by Pavneet-Sing** [comment]
Without any doubt , i like the concept of immutability and cute builder patterns .it is a great work and very well explained.

**Pull request closed without merging**
