### PR TITLE
Add middleware layer and some unit tests

### LINKED ISSUE #8: Provides middlewares feature from redux
The middlewares is a good place to handle some async operations without overload the ActionCreators.

### PR DESCRIPTION
**Pull request by niltonvasques**
Hello there.

We are bulding an [application](https://github.com/Catbag/redux-android-sample) with this lovely library and we start to add some async calls directly on ActionCreators. However they start to becomes bigger and with many responsibilities. Reading redux documentation we have found that middleware is the approach that they found to handle those calls.

So I've done some effort to provide Middleware's support in Fluxxan library as well. And to change the code with more confidence, I've written some unit tests. 
 
Middleware is best suited to handle async operations.
A complete explanation can be found in the original [Middleware's](http://redux.js.org/docs/advanced/Middleware.html) docs published by redux project.

### Follow the list of things included on this PR:

* Upgrade build tools to 23.0.3
* Upgrade maven gradle plugin to 1.4.1
* Upgrade gradle to 2.2.2
* Remove local android studio files files from repo
* Write unit tests for Fluxxan class
* Write tests for add, remove, start and stop methods from fluxxan
* Write simple dispatcher tests
* Create a base middleware to store dispatcher
* Create register and unregister middleware tests
* Write tests to evaluates if intercept method from middleware is called after dispatch
* Adjust javadocs in middleware class and remove unused deps
* Let register middlewares through fluxxan class
* Don't allow register two middlewares from same class
* Upgrade readme with middlewares section
* Change demo app to includes a logger middleware sample

Fixes #8

### CODE REVIEW

**Comment by thedumbtechguy** [comment]
Hi.

This looks really great. I'm yet to look at it, but it looks like some really great work.
I really appreciate it. Especially the tests!

Let me check it out and merge it in.

**Comment by niltonvasques** [comment]
Thanks @frostymarvelous. Feel free to make any comments/suggestions in the patch.

**Comment by thedumbtechguy** [comment]
This is awesome. 

You saved me on 2 aspects, 
1. I wrote this to be testable, but never got round to doing it. I really really appreciate the work put in here. 
2. I always wanted to add middlewares. Main aim being to add a time travel debugger middleware. 

I do have a suggestion. 
- Change `intercept` to `before(action, state)`. 

This is necessary as I'd like to add a couple of things and I'd like the api to be consistent. 
1. `after(action, oldState, newState)` (critical for time traveling). 
2. `error(action, state, exception)`

**Comment by niltonvasques** [comment]
Wow, it's good to know that some changes proposed in this PR already was in your roadmap.

I totally agree with your suggestions to change `intercept` to `before`, since you are planning to have an `after` method. 

This will help in another use case that me and my partners are discussing. We are planning to handle persistence of AppState in middlewares, but actually middlewares only is called before AppState change. We are thinking in have a hybrid middleware that implements StateListener to catch actions before and after. But your solution looks too much better.

I will rename the `intercept` method asap.

**Comment by thedumbtechguy** [comment]
Awesome work!

Thank you so much.

**Pull request merged**
